ip_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: IPUserBundle:Default:index }

ip_user_create:
    path:     /users/create
    defaults: { _controller: IPUserBundle:Create:index }
